Project delete
zazuko/cube-creator pull request #1223
Opened 2022-05-19 14:30 UTC by tpluscode

I found two cases when deleting resources would leave some dangling leftovers

1. When removing a column mapping, the dimension mapping would not be removed
2. When deleting the entire project, a lot was not removed

In the latter case I opted for simply dropping all graphs which share the project's URL stem (all resources are named as `https://{Project URL}/{child resource path}`

2022-05-19 15:05 UTC, cristianvasquez commented on apis/core/test/domain/cube-projects/delete.test.ts
> +    await expect(anyGraph).to.eventually.deep.equal([])
Could we have some data supposed to remain? 

- Given : data type A, data type B
- When: Delete data type A
- Then: Remain data type B

To check if this doesn't delete all.

2022-05-19 15:22 UTC, cristianvasquez commented
I support the simplicity of the solution.

But If we rely on URL patterns for the graphs, we could have the logic of minting graph names centralized so that one can look up the  Stem of each entity and they are not spread around. In the particular case of Projects,  https://{Project URL}/{child resource path}

it could have methods,  newGraphUri(type Project) & stem(type Project)

2022-05-19 15:59 UTC, cristianvasquez requested changes
To add a test:

    Given: data type A, data type B
    When: Delete data type A
    Then: Data type B remains

To check if this method doesn't delete all after some weird URL pattern change.

2022-05-24 06:57 UTC, tpluscode commented
> But If we rely on URL patterns for the graphs, we could have the logic of minting graph names centralized [...]

Indeed, identifiers should be created [here](https://github.com/zazuko/cube-creator/blob/master/apis/core/lib/domain/identifiers.ts)

2022-05-24 06:59 UTC, cristianvasquez commented
I was not aware of that one, It was just in case :)

2022-05-24 08:09 UTC, cristianvasquez approved these changes

2022-05-24 10:14 UTC, merged