Use cubelink shapes
zazuko/cube-creator pull request #1471
Opened 2023-10-25 07:24 UTC by giacomociti

2023-10-25 13:38 UTC, tpluscode requested changes
Looks good overall. 
I'm only thinking about the version increment. This is a big change and I'd say we bump major of the CLI and API.

2023-11-07 19:55 UTC, tpluscode requested changes

2023-11-07 19:55 UTC, tpluscode commented on cli/shapes.ttl
> +    sh:node <http://example.org/ObservationConstraintShape> ; # from cube.link
`v0.1.0` of cube-link has been published, which removes `example.org`

2023-11-08 16:38 UTC, Rdataflow commented
@giacomociti great 👍️

2023-11-08 19:59 UTC, tpluscode approved these changes

2023-11-09 13:00 UTC, merged