Date published
zazuko/cube-creator pull request #1513
Opened 2024-05-14 07:29 UTC by giacomociti

should fix https://github.com/zazuko/cube-creator/issues/1502

2024-05-15 09:57 UTC, tpluscode requested changes
I think it's important to add a test to the e2e run

2024-05-17 09:26 UTC, giacomociti commented
> I think it's important to add a test to the e2e run

do you mean API or UI e2e test?

2024-05-17 09:47 UTC, tpluscode commented
> > I think it's important to add a test to the e2e run
> 
> do you mean API or UI e2e test?

Neither. I meant the publish pipeline run in cli/test/lib/commands/publish.test.ts

2024-06-03 09:31 UTC, tpluscode approved these changes

2024-06-03 09:35 UTC, merged