WIP feat: download csv
zazuko/cube-creator pull request #464
Opened 2021-01-27 10:03 UTC by lucafurrer

Allow the download of uploaded CSVs

2021-01-27 10:04 UTC, lucafurrer commented on apis/core/lib/handlers/csv-source.ts
> +  res.header('Location', directDownload)
@tpluscode I run into CORS-Problems using redirect and still wondering if there is a better way than this.

2021-01-29 15:31 UTC, tpluscode requested changes

2021-01-29 15:31 UTC, tpluscode commented on ui/src/api/mixins/CSVSource.ts
> +        download: ns.cc.GetCSVSourceAction
```suggestion
        download: schema.DownloadAction
```

2021-01-29 15:31 UTC, tpluscode commented on packages/core/namespace.ts
> +  'GetCSVSourceAction'
Won't need a custom type. Can use `schema` (see other comment)

2021-01-29 15:31 UTC, tpluscode commented on ui/src/components/CsvSourceMapping.vue
> +    window.open(downloadLink)
I don't think this belongs to the component. Please move `window.open` to `store/modules/project.ts`

2021-01-29 15:31 UTC, tpluscode commented on apis/core/hydra/csv-source.ttl
> +        "Get CSV" ;
```suggestion
        "Download CSV" ;
```

maybe?

2021-01-29 18:03 UTC, merged