feat(csv): get csv head via api
zazuko/cube-creator pull request #50
Opened 2020-10-12 12:05 UTC by lucafurrer

When making a request on a `CSVSource` with ContentType "text/csv", the header + 20 random(?) rows are returned.
For all other requests the usual Hydra Get is called and returns the node as triples.

`.addOut(cc.s3Key, key)`
Is also contained in the contentUrl, but I think it is better to store it explicitly. If anyone has a better existing property, I am open for suggestions.

2020-10-12 12:10 UTC, vhf commented
> the header + 20 random(?) rows are returned.

https://github.com/zazuko/cube-creator/blob/fc633f919d2365905c7caba3c85e60928ef8f6f8/apis/core/lib/storage/s3.ts#L48

20 unique lines including the header

2020-10-12 13:03 UTC, tpluscode requested changes

2020-10-12 13:07 UTC, lucafurrer commented on apis/core/lib/handlers/csv-source.ts
> +export const getCSVSource = labyrinth.protectedResource(
No

2020-10-12 13:11 UTC, lucafurrer commented on apis/core/lib/domain/csv-source/upload.ts
> +    .addOut(cc.s3Key, key)
I like this idea!

2020-10-12 13:12 UTC, lucafurrer commented on apis/core/lib/handlers/csv-source.ts
> +export const getCSVSource = labyrinth.protectedResource(
No

2020-10-12 20:18 UTC, lucafurrer commented
To make the unit-test run properly I made a refactoring for loadFileHeadString
- moved it away from the class s3
- takes a stream as input
```TypeScript
export function loadFileHeadString(
  stream: Readable,
  uniqueLines = 20,
): Promise<string> 
```

The access to S3 is not covered by unit tests anymore. In my opinion this has to be done through integration testing and is covered by the e2e tests.

2020-10-13 06:33 UTC, tpluscode commented on apis/core/lib/handlers/csv-source.ts
> +    if ((!req.headers['content-type'] || !is(req.headers['content-type'], 'text/csv'))) {
This would be the simplest approach
```suggestion
    if (!typeis(req, 'text/csv')) {
```

2020-10-13 06:34 UTC, tpluscode commented on apis/core/lib/handlers/csv-source.ts
> +import { is } from 'type-is'
If you default-import

```suggestion
import typeis from 'type-is'
```

2020-10-13 06:35 UTC, tpluscode commented on apis/core/lib/domain/identifiers.ts
> +}
Is this used?

Besides, I think that we can just keep a blank node for the `MediaObject`

2020-10-13 06:37 UTC, tpluscode commented on apis/core/test/domain/csv/parse.test.ts
> +    const input1 = fileContent.toString()// await loadFileString('test/CH_yearly_air_immission_basetable.csv')
```suggestion
    const input1 = fileContent.toString()
```

2020-10-13 06:38 UTC, tpluscode commented on apis/core/test/domain/csv/parse.test.ts
> +import fss, { promises as fs } from 'fs'
I don't see `fss` used, do I?

2020-10-13 10:54 UTC, merged