feat: delete csv-source
zazuko/cube-creator pull request #93
Opened 2020-10-23 11:37 UTC by lucafurrer

Delete a CSV-Source
Does:
- Remove file from S3
- Delete graph of csv.source

Does not (yet): 
- Delete associated tables or prevent deletion when tables are present

2020-10-23 13:33 UTC, lucafurrer commented on apis/core/lib/ResourceStore.ts
> +    this.__deletedGraphs.add(id)
Should we remove all nodes of this graph from the store at this moment?

2020-10-23 13:34 UTC, lucafurrer commented on apis/core/lib/domain/csv-source/delete.ts
> +  // Delete them
I suggest to wait until the table implementation is done, to continue on this

2020-10-23 13:35 UTC, lucafurrer commented on apis/core/test/ResourceStore.test.ts
> +      expect(client.query.update).to.have.been.calledOnce
@tpluscode what would be the good way to check that the graph does not exist anymore?

2020-10-23 13:36 UTC, lucafurrer commented on apis/core/hydra/csv-source.ttl
> +            <file:handlers/csv-source#remove> ;
Somehow the compiler was not too happy with a function called delete in the handler...

2020-10-23 13:40 UTC, lucafurrer commented on e2e-tests/csv-source/delete.hydra
> +            Expect Status 404
I would expect a 404 but a 405 is returned. Not sure if we should adapt the test or if there is a bug somewhere

2020-10-26 08:05 UTC, tpluscode requested changes

2020-10-26 08:43 UTC, lucafurrer commented on apis/core/test/support/TestResourceStore.ts
> +    this.__deletedGraphs = new TermSet()
It is private...

2020-10-26 08:49 UTC, tpluscode commented on apis/core/test/support/TestResourceStore.ts
> +    this.__deletedGraphs = new TermSet()
The underscores is a convention which we don't enforce, but maybe we should. Ok, forget my suggestion for now

2020-10-26 09:07 UTC, lucafurrer commented on e2e-tests/csv-source/delete.hydra
> +            Expect Status 404
From a zulip discussion with @tpluscode 
`hydra-box looks up resources+operations by checking a resource named X (that is obviously getting removed) but then it also looks up resources used as objects by other resources. in our case it is a leftover <csv-mapping> cc:csvSource <deleted-source>`

2020-10-26 10:01 UTC, lucafurrer commented on apis/core/lib/domain/csv-source/delete.ts
> +  // Delete them
Done -> #97

2020-10-26 15:58 UTC, martinmaillard approved these changes

2020-10-26 16:20 UTC, tpluscode approved these changes

2020-10-26 16:21 UTC, tpluscode commented
Will also need a rebase or merge master

2020-10-26 16:25 UTC, lucafurrer commented
I did it 1 hour ago, but here we go again

2020-10-26 16:48 UTC, merged